feat: Parse all id token claims into raw_claims, so they are availabl…
ory/docs pull request #1010
Opened 2022-09-28 08:50 UTC by pr1ze

…e in the jsonnet context during registration. Fixing issue #2528 https://github.com/ory/kratos/issues/2528

Docs for https://github.com/ory/kratos/pull/2765 which should be merged and released first

## Related Issue or Design Document
[#2528](https://github.com/ory/kratos/issues/2528)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

## Further comments

Docs for https://github.com/ory/kratos/pull/2765 which should be merged and released first

2022-09-28 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/docs?pullRequest=1010) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/docs?pullRequest=1010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/docs?pullRequest=1010) it.</sub>

2022-09-28 14:46 UTC, jonas-jonas requested changes
Just a few formatting & mark-up issues. Otherwise, looking really solid! Thanks!

2022-09-28 14:46 UTC, jonas-jonas commented on docs/kratos/social-signin/90_data-mapping.mdx
> +  RawClaims           map[string]interface{}  `json:"raw_claims,omitempty"`
```suggestion
    RawClaims           map[string]interface{}  `json:"raw_claims,omitempty"`
```

The formatting is off here.

2022-09-28 14:46 UTC, jonas-jonas commented on docs/kratos/social-signin/90_data-mapping.mdx
> +All claims that are not part of the standard userinfo claims, are mapped into raw_claims. An example of mapping a Raw Claim called
```suggestion
All claims that are not part of the standard userinfo claims, are mapped into `raw_claims`. An example of mapping a raw claim called
```

2022-09-28 14:46 UTC, jonas-jonas commented on docs/kratos/social-signin/90_data-mapping.mdx
> +groups:
```suggestion
"groups":
```

2022-10-04 06:38 UTC, aeneasr commented
I tried pushing some changes required for merging the PR to your fork & branch, but it appears that I am not allowed to do so 😕 

```
% git push ...
ERROR: Permission to push denied to aeneasr.
fatal: could not read from the remote repository.

Please make sure that you have the correct access rights
and the repository exists.
```

But the good news is, giving access is easy! :relaxed: All you need to do is [enable write access for maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). Thank you! 😄

If the repository belongs to an organization, please add me for the [project as a collaborator](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization)!

2022-10-05 05:55 UTC, closed without merging

2022-10-05 06:24 UTC, pr1ze commented
We have fixed the permissions issues now @aeneasr :) It looks like the PR is closed without being merged?

2022-10-05 06:27 UTC, aeneasr commented
Yes, but the changes are on master. I pushed my changes to a different branch / PR :)

https://github.com/ory/docs/commit/fcbb06eba40c6d45ae932b019a21eb4688c3b219