feat: add draft guide on implementing ory elements with new/existing project
ory/docs pull request #1032
Opened 2022-10-11 14:40 UTC by GabeCurran

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2022-10-11 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/docs?pullRequest=1032) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/docs?pullRequest=1032) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/docs?pullRequest=1032) it.</sub>

2022-10-11 14:40 UTC, GabeCurran commented
Addressing This Issue:
https://github.com/ory/docs/issues/1004

2022-10-17 15:07 UTC, Benehiko requested changes

2022-10-17 15:07 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +```
We can use a codeblock instead I think 
https://github.com/ory/docs/blob/master/docs/getting-started/integrate-auth/vue.mdx?plain=1#L50

2022-10-17 15:07 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +
I don't think we need new headings for these. I think make it one codeblock and add line highlighting to the parts where we are using the sdk and elements.

https://docusaurus.io/docs/markdown-features/code-blocks#line-highlighting

2022-10-18 14:21 UTC, Benehiko requested changes

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +```
Move down to when we run the app

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +...
replace with remote code block

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +### Create sdk.ts
use a different header since it's under the ### Setting up Our App

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +- And it wraps the application with Ory Elements <ThemeProvider />
this should be `main.tsx`

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +)
replace with remote code

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +```
we can remove it

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +```
Remote code block

2022-10-18 14:21 UTC, Benehiko commented on docs/getting-started/integrate-auth/react-with-elements.mdx
> +```
Remote code block

2022-10-20 09:25 UTC, Benehiko submitted a review, later dismissed

2022-10-28 14:26 UTC, tomekpapiernik commented
React desc. bundled with preact in one doc: 
https://github.com/ory/docs/pull/1046

2022-10-31 12:17 UTC, Benehiko commented
> React desc. bundled with preact in one doc: #1046

@tomekpapiernik Should this PR then be closed? Also is there anything from this PR that @GabeCurran can carry over to the new docs https://www.ory.sh/docs/getting-started/custom-ui-preact-ory-elements?

2022-11-02 08:35 UTC, tomekpapiernik commented
@Benehiko as we discussed recently, the content of this guide has been covered in #1046 . 
However, I see that you guys added some new information reg. Ory Tunnel, so I might take that and add it in a separate PR.
Closing this PR now.

2022-11-02 08:35 UTC, closed without merging