fix: compliance docs update
ory/docs pull request #1158
Opened 2022-12-13 13:49 UTC by vinckr

- fix: threat models doc update
- fix: security section sidebar
- chore: fix typos
- chore: missing feature

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2022-12-15 14:13 UTC, tomekpapiernik requested changes

2022-12-15 14:13 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +Ory Network provides Ory Identities with protection against brute force attacks by rate-limiting requests to API public endpoints,
```suggestion
Ory Network provides Ory Identities with protection against brute-force attacks by rate limiting requests to API public endpoints,
```
Adjective b4 noun = hyphen
rate limiting = no hyphen (I know Grammarly tells you to use a hyphen, but "rate limiting" here is not describing a quality of "requests")

2022-12-15 14:13 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +rate-limiting or other measures to ensure the security of the network.
Mixing Ory Network and self-hosted instances

2022-12-15 14:13 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +## Password Policy
```suggestion
## Password policy
```

2022-12-15 14:13 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +To learn more about setting up a secure password policy, please refer to the
```suggestion
To learn more about setting up a secure password policy, refer to the
```

No need to be overly polite

2022-12-15 14:13 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +existing password.
Technically changing passwords is possible only when users have a privileged session. To get a privileged session, users must authenticate. Do you think that it's a good idea to describe this?

2022-12-16 10:14 UTC, vinckr commented on docs/kratos/concepts/security.mdx
> +## Brute-force defenses
It is defense **against** brute-force. 

If I write **anti-brute force defense**, I am defending against anti-brute force attacks (?)

2022-12-16 10:41 UTC, vinckr commented on docs/kratos/concepts/security.mdx
> +attack surface, the likelihood, and the impact of an attack.
```suggestion
Working with and administering software that stores personal information carries risk. It is important to identify threats and understand the system's
attack surface, the likelihood, and the impact of an attack.
```

?

2022-12-16 11:00 UTC, vinckr commented on docs/kratos/concepts/security.mdx
> +analyzing threats and implementing security measures for Ory Identities and self-hosted Ory Kratos Identity Server.
I think in this instance it is OK 😅

2022-12-19 08:38 UTC, tomekpapiernik commented on docs/kratos/concepts/security.mdx
> +## Brute-force defenses
Yes, that's what it does. But looking at this after a few days it doesn't really sound right. The best solution would be to use a heading that is constructed a bit differently than the rest: 

`Defenses against brute-force attacks`

2022-12-19 08:59 UTC, vinckr commented on docs/kratos/concepts/security.mdx
> +## Brute-force defenses
done!

2022-12-20 12:37 UTC, tomekpapiernik approved these changes
Looks good to me now. Go ahead and merge at your discretion. :)

2022-12-20 12:51 UTC, merged