docs: update identity schema sections
ory/docs pull request #1167
Opened 2022-12-19 11:02 UTC by aeneasr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2022-12-23 11:34 UTC, aeneasr commented
This PR restructures the identity model nav bar:

- a quick **overview** of the identity model with an example
- what the **identity schema** is, and giving our presets as examples
- how to **customize the identity schema**
- how to manage identity schemas on the ory network
- best practices around identity modelling

2022-12-28 15:10 UTC, tomekpapiernik submitted a review, later dismissed

2022-12-28 16:59 UTC, aeneasr reviewed
Thank you @tomekpapiernik , looked over your changes and only found nit-picks :) Can also change them myself :)

2022-12-28 16:59 UTC, aeneasr commented on docs/identities/model/manage-identity-schema.mdx
> +## Creating identity schemas
I think we can omit the headline or make it h1 :) Otherwise we have a H1 directly followed by a H2. WDYT?

2022-12-28 16:59 UTC, aeneasr commented on docs/kratos/manage-identities/15_customize-identity-schema.mdx
> +![Registration screen with username, first name, and last name.](../_static//customize-identity-schema/1.png)
Looks like a duplicate `//` slipped in :)

2022-12-29 08:34 UTC, aeneasr commented on docs/identities/model/manage-identity-schema.mdx
> +## Creating identity schemas
```suggestion
# Creating identity schemas
```

2022-12-29 08:34 UTC, aeneasr commented on docs/kratos/manage-identities/15_customize-identity-schema.mdx
> +![Registration screen with username, first name, and last name.](../_static//customize-identity-schema/1.png)
```suggestion
![Registration screen with username, first name, and last name.](../_static/customize-identity-schema/1.png)
```

2022-12-29 08:37 UTC, tomekpapiernik requested changes
PLS don't merge yet! I'm working on some updates for 
[docs/kratos/manage-identities/15_customize-identity-schema.mdx](https://github.com/ory/docs/pull/1167/files#diff-75044717b45f3a3cbb224c934b65f7753b2917760ba8770a951c6974dbccefd6) ;)

2022-12-29 10:12 UTC, tomekpapiernik approved these changes

2022-12-29 10:13 UTC, merged