docs: explain csrf defenses
ory/docs pull request #1232
Opened 2023-01-26 15:07 UTC by vinckr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-01-27 13:30 UTC, aeneasr commented on docs/kratos/concepts/security.mdx
> +against CSRF attacks.
This isn't correct unfortunately. CSRF can happen without a session too. One such attack is login csrf ( https://support.detectify.com/support/solutions/articles/48001048951-login-csrf )
. We deploy regular CSRF counter measures as explained here:

- https://owasp.org/www-community/attacks/csrf
- https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

Instead of making the session cookie CSRF resistant, we have a dedicated CSRF cookie whose purpose it is to protect against CSRF, even if no session exists yet.

2023-01-27 13:30 UTC, aeneasr requested changes
See comment

2023-01-27 16:07 UTC, vinckr commented on docs/kratos/concepts/security.mdx
> +against CSRF attacks.
> Instead of making the session cookie CSRF resistant

We still use the [sameSite attribute](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#samesite-cookie-attribute) as well though, right? 

Is the dedicated CSRF cookie what they describe in "[Double Submit](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie)" cookie?
or what they describe under Login CSRF?

> Login CSRF can be mitigated by creating pre-sessions (sessions before a user is authenticated) and including tokens in login form. 

If it is really complex to describe here, maybe it is not worth it to go in such detail and just say there are multiple protections against multiple threat vectors regarding CSRF?

2023-01-30 10:06 UTC, aeneasr commented on docs/kratos/concepts/security.mdx
> +against CSRF attacks.
No we use https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern

2023-01-30 15:02 UTC, vinckr commented
Thanks for the clarification!


- Rewrote the CSRF text to clarify that we mainly use the anti-csrf cookie
- Removed the "What is CSRF" section from the troubleshooting doc and moved that content also to the Threat models doc

This way you can learn about CSRF and how Ory protects against it in the threat models doc and the troubleshooting is just focused on how to fix errors related to that.

Feel free to take another look :)

2023-01-31 08:31 UTC, fbolton approved these changes
Text and layout looks good to me.

2023-02-02 10:31 UTC, vinckr commented
Can you please take a quick look before we merge @aeneasr ?

2023-02-02 10:39 UTC, aeneasr approved these changes
Great!

2023-02-02 16:52 UTC, merged