Update webhook documentation with more grant types
ory/docs pull request #1241
Opened 2023-02-04 17:13 UTC by sgal

## Related Issue or Design Document

Documentation update for https://github.com/ory/hydra/pull/3427.

This change adds guides for adding/updating custom token claims via webhook feature for the following set of grant types:
- `authorization_code`
- `client_credentials`
- `refresh_token`
- `urn:ietf:params:oauth:client-assertion-type:jwt-bearer`

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-02-04 17:24 UTC, sgal commented
Updated docs page at Preview - https://docs-rnke3r89h-ory.vercel.app/docs/hydra/guides/custom-token-claims

2023-02-27 12:35 UTC, tomekpapiernik requested changes

2023-03-03 12:19 UTC, sgal commented on docs/hydra/guides/custom-token-claims.mdx
> +- `urn:ietf:params:oauth:client-assertion-type:jwt-bearer` - see [RFC7523](https://www.rfc-editor.org/rfc/rfc7523)
Makes sense to shorten the name 👍 It is an OAuth2 grant, see https://www.rfc-editor.org/rfc/rfc7523.

2023-03-03 12:46 UTC, sgal commented
@tomekpapiernik Thanks for the review. I reverted the document ID and the sidebar changes and fixed the writing. Please have a look.

2023-03-06 12:52 UTC, tomekpapiernik commented
Thanks for updating your PR @sgal ! I took the liberty of editing this a bit more. Most important change - I updated the Ory CLI to use --add instead of --replace, as the keys you want to work with aren't present in the oauth2 config from the get-go - they must be added. The --replace command doesn't do that. I'll approve this PR and it can be merged along with the code PR you opened.

2023-03-06 12:52 UTC, tomekpapiernik submitted a review, later dismissed

2023-03-06 15:49 UTC, sgal commented
@tomekpapiernik Thanks a lot for the review and fixes 👏

2023-04-25 11:14 UTC, hperl approved these changes
LGTM, thanks for your contribution @sgal!

2023-04-25 11:20 UTC, merged