docs: greenfield native use case
ory/docs pull request #1343
Opened 2023-03-28 10:17 UTC by fbolton

First draft of the Greenfield native app use case docs.
Related issue is: https://github.com/ory/usecase-docs/issues/26
Related epic is: https://github.com/ory/usecase-docs/issues/24

2023-03-30 13:23 UTC, tomekpapiernik requested changes

2023-03-30 13:23 UTC, tomekpapiernik commented on docs/use-cases/greenfield-native.md
> +   provides a platform-neutral framework for building mobile apps on Android and iOS. The developer soon located Ory's
```suggestion
   provides a platform-agnostic framework for building mobile apps on Android and iOS. The developer soon located Ory's
```

I think that "platform-agnostic" is a more common term.

2023-03-30 13:23 UTC, tomekpapiernik commented on docs/use-cases/greenfield-native.md
> +   registrations.
This thing is repeated quite for the third (?) time at this point without giving more details.

2023-03-30 13:23 UTC, tomekpapiernik commented on docs/use-cases/_static/greenfield-native.svg
- The computer icon has grey padding around it as already indicated in another use case PR. 
- The diagram itself isn't really clear. For example, what does the "Ory CLI" arrow point to? What is the "Ory Console backend"? Isn't Ory Network the backend here? 🤔 
- There should be "Identity Schema" not "Identities Schema". Also, what is it "connected" to?

2023-03-30 13:23 UTC, tomekpapiernik commented on docs/use-cases/greenfield-native.md
> +- [Account Verification](https://www.ory.sh/docs/kratos/self-service/flows/verify-email-account-activation)
I don't think that both words in self-service flow names should be capitalized.

2023-04-03 09:15 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +### Elaborate and customize the app
I went for "Extend" as it's less clunky than "Further develop" (and I already used it in the first paragraph).

2023-04-03 09:15 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +At this point, the developer team at ACME Corporation were ready to extend the functionality of the app and customize the features
Done.

2023-04-03 09:27 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +   provides a platform-neutral framework for building mobile apps on Android and iOS. The developer soon located Ory's
Ngram suggests otherwise: https://books.google.com/ngrams/graph?content=platform-neutral%2Cplatform-agnostic&year_start=1950&year_end=2008&corpus=en-2012&smoothing=3

But I think both are good.

2023-04-03 09:29 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +- [Account Verification](https://www.ory.sh/docs/kratos/self-service/flows/verify-email-account-activation)
Sure. Generally, it's good to use sentence case as much as possible.

2023-04-03 09:32 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +1. Before going into production, ACME Corporation upgraded Ory Network to a paid subscription tier. The paid subscription tier is
Ok, also noted that it's a prerequisite for the custom domain.

2023-04-03 09:35 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +   registrations.
Ok, I left out the mention of accelerated user registrations in this step.

2023-04-03 09:52 UTC, fbolton commented on docs/use-cases/_static/greenfield-native.svg
I made a couple of tweaks, but this diagram needs further refinement in any case. Ultimately the goal is to base it on Figma components created by John.

The question of what to call the "Ory Console backend" is interesting -- AFAIK we don't really have an official name for this component. Patrik was happy enough with "Ory Console backend", but maybe we should ask Klaus what he thinks.

2023-04-03 09:55 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +## Use case: ACME Corporation is new to security and wants to implement a straightforward authentication solution for their native app
Yes, I don't think we can actually use this as a title either. It depends on how we ultimately present the use cases. You can think of it as a working title for now.

2023-04-03 10:38 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +existing browser-based app has convinced ACME that social sign-in leads to much better conversion rates.
I expanded this section to give a brief explanation of social sign-in, for any readers who are not familiar with the concept. In particular, the revised section should clarify why social sign-in leads to better conversion rates.

2023-04-03 11:21 UTC, tomekpapiernik commented on docs/use-cases/_static/greenfield-native.svg
About "Ory Console backend" - disregard that comment please, I was wrong. Got some explanations from PM and there is indeed an "intermediary layer" between the console and the services. Sorry!

2023-04-03 11:42 UTC, tomekpapiernik commented on docs/use-cases/greenfield-native.md
> +1. The app developer created a new project in Ory Console, choosing the US hosting location.
I'll explain this in a DM ;)

2023-04-04 12:54 UTC, fbolton commented on docs/use-cases/greenfield-native.md
> +1. The app developer created a new project in Ory Console, choosing the US hosting location.
I revised the sentence to "choosing the US location for hosting PII data", so I think it makes sense now.

2023-04-13 15:11 UTC, fbolton commented on docs/use-cases/_static/greenfield-native.svg
Updated diagram with multiple improvements.

2023-05-04 11:21 UTC, closed without merging