fix python sdk config issue
ory/docs pull request #1399
Opened 2023-05-11 11:41 UTC by DanielNwaeze

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-05-11 11:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/docs?pullRequest=1399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/docs?pullRequest=1399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/docs?pullRequest=1399) it.</sub>

2023-05-12 09:47 UTC, vinckr reviewed
Thanks @DanielNwaeze 
this looks great! 
Can you please sign the CLA as well, then I do a final review and merge. 

Thanks again 🙌

2023-05-12 10:41 UTC, DanielNwaeze commented
I have signed the CLA, thanks @vinckr

2023-05-12 13:52 UTC, vinckr requested changes
Thanks! 
2 small things: 

- Can you move the document to docs/keto/sdk/ please, since the example is for permissions
- minor formatting issue I marked below

2023-05-12 13:52 UTC, vinckr commented on docs/kratos/sdk/10_python.mdx
> +* Bearer Authentication (oryAccessToken):
```suggestion
## CheckPermission

As an example, let's check for whether a given subject has the necessary permissions.

### Example

- Bearer Authentication (oryAccessToken):
```

Just some formatting issues.

2023-05-12 14:07 UTC, DanielNwaeze commented
@vinckr  i have made the necessary changes

2023-05-12 14:13 UTC, vinckr approved these changes

2023-05-12 14:14 UTC, vinckr commented
awesome thanks so much for the contribution @DanielNwaeze 
I will fix the format and sidebar in a followup PR, bc that is always a bit annoying to do when you do not have write access here.

2023-05-12 14:14 UTC, merged

2023-05-12 16:06 UTC, DanielNwaeze commented
No problem, it's fine. Thank you for the merge @vinckr