feat: add Ory Network CORS documentation
ory/docs pull request #1449
Opened 2023-07-10 13:48 UTC by zepatrik

This is very minimal right now, but I was not sure what else to add.

2023-07-10 13:49 UTC, kmherrmann submitted a review, later dismissed
Nice, thanks!
Once we ship the corresponding Console screen, let's amend the docs accordingly.

2023-07-10 14:02 UTC, vinckr requested changes
Avoid the We form. [Avoid we](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/we)from MS styleguide

+ a few more minor issues

2023-07-10 14:02 UTC, vinckr commented on docs/guides/cors.mdx
> +Custom domains can be configured to use specific CORS settings. Head over to the [Custom Domains](./custom-domains.mdx#cors)
```suggestion
You can configure custom domains to use specific CORS settings. Head over to the [Custom Domains](./custom-domains.mdx#cors)
```

Avoid passive when possible

2023-07-10 14:05 UTC, vinckr commented on docs/guides/cors.mdx
> +You can find more information about the `ory patch` command in the [Ory CLI documentation](./cli/10_ory_cli.mdx).
```suggestion
You can find more information about the `ory patch` command in the [Ory CLI documentation](./cli/ory-patch).
```

What did you want to link here? there 10_ory_cli doesnt exist I think

2023-07-11 08:55 UTC, aeneasr commented
What do you think of moving the CORS document under the API section? https://www.ory.sh/docs/api/

2023-07-11 12:38 UTC, zepatrik commented
> What do you think of moving the CORS document under the API section? https://www.ory.sh/docs/api/

I don't really care, wherever you think it makes most sense.

2023-07-11 12:58 UTC, aeneasr commented
ok let's move it there i think it makes sense

2023-07-17 11:14 UTC, merged