docs: redirect duplicate doc
ory/docs pull request #1488
Opened 2023-08-03 14:48 UTC by vinckr

- fix: move oauth login flow description
- fix: redirect old doc and delete

as proposed moves the missing flow steps to the new oauth2 login doc, redirects and deletes the old doc.

closes https://github.com/ory/docs/issues/1389

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-08-04 08:02 UTC, aeneasr requested changes
HTTP is so 1995 - please always use HTTPS :)

And follow the rules: https://github.com/ory/docs#placeholders-and-dummy-data

2023-08-04 08:02 UTC, aeneasr commented on docs/oauth2-oidc/custom-login-consent/flow.mdx
> +   the Consent Provider, hosted at - for example - `http://consent-service/consent?consent_challenge=4567...`
```suggestion
   the Consent Provider, hosted at - for example - `https://example.org/oauth2-screens/consent?consent_challenge=4567...`
```

2023-08-04 08:02 UTC, aeneasr commented on docs/oauth2-oidc/custom-login-consent/flow.mdx
> +   `http://<your-ory-network-project>/oauth2/auth?client_id=...&...&consent_verifier=7654...`.
```suggestion
   `http://https://{project-slug}.projects.oryapis.com/oauth2/auth?client_id=...&...&consent_verifier=7654...`.
```

2023-08-04 09:21 UTC, vinckr commented
AH right, thanks for keeping an eye out for this! Will see to keep our own styleguide more in mind 😁

2023-08-08 09:31 UTC, aeneasr submitted a review, later dismissed

2023-08-22 10:01 UTC, vinckr commented
should be ready now @aeneasr

2023-08-22 10:23 UTC, aeneasr approved these changes

2023-08-22 10:23 UTC, merged