feat: add CTA to ory network
ory/docs pull request #1499
Opened 2023-08-10 13:11 UTC by LBBO

This CTA differs a bit from the design in the interest of saving time.

2023-08-10 13:57 UTC, aeneasr commented
Isn't this missing some button i can click on?

2023-08-10 17:27 UTC, LBBO commented
Fixed. Apparently the docusaurus production build just deletes `@container` queries, lol. But there ended up being no necessity for them, so I just exchanged them for equivalent media queries.

2023-08-10 18:53 UTC, OryTiki requested changes
Still need some work on the button styling or content to ensure most viewports look good. 

<img width="268" alt="image" src="https://github.com/ory/docs/assets/126667408/ba43a2a5-1334-4e69-ab0c-3ea5f57ab4bb">

2023-08-22 09:30 UTC, jfcurran requested changes
the button text should be centered, this change will do the trick

2023-08-22 09:30 UTC, jfcurran commented on src/components/OryNetworkCta/ory-network-cta.css
> +    display: block;
```suggestion
    display: block;
    text-align: center;
```

2023-08-22 10:00 UTC, vinckr reviewed
lgtm. 

only nit is that its not present in the "self-hosting" category, is that on purpose?

2023-08-22 10:20 UTC, aeneasr commented
@vinckr it's only visible if there is a table of contents on the right side: https://docs-fgqd0n2bm-ory.vercel.app/docs/ecosystem/configuring

2023-08-22 10:21 UTC, merged