feat: add docs for native sign in using Apple SDK
ory/docs pull request #1528
Opened 2023-09-06 16:30 UTC by jonas-jonas

## Related Issue or Design Document

https://github.com/ory/kratos/pull/3476

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-09-12 13:05 UTC, jonas-jonas commented
Pls don't merge yet, not on Ory Network yet.

Google is not implemented yet, will do next!

2023-09-12 13:47 UTC, Benehiko requested changes
Could you also link the documentation to here from https://docs-cazi73gk0-ory.vercel.app/docs/kratos/social-signin/native-apps? Since it is now possible to have complete native flows instead of browser in native apps.

2023-09-12 13:47 UTC, Benehiko commented on docs/kratos/social-signin/30_apple.mdx
> +integrate with Ory.
Always positive! :)

```suggestion
This flow uses the native Apple SDK and does not require a browser. This results in an issued `id_token`  on the client side which is exchanged at Ory for a session token.
```

2023-09-12 13:47 UTC, Benehiko commented on docs/kratos/social-signin/30_apple.mdx
> +integrate with Ory.
Move the limitations and drawbacks to a section at the end.

2023-09-12 13:47 UTC, Benehiko commented on docs/kratos/social-signin/30_apple.mdx
> +1. Ory will validate the `id_token` and create an identity and optionally a session (if configured).
```suggestion
1. Configure an Apple social sign-in provider in Ory using the same `client_id` as in your native app.
2. Generate a random value that you can use as a `nonce`.
3. Obtain an `id_token` from Apple using the Apple SDK. Make sure to also submit the SHA256 encrypted `nonce`.
4. Submit the `id_token` and `nonce` (as the `raw_id_token_nonce`) as part of the `updateRegistrationFlow` or `updateLoginFlow`
   request to Ory.
5. Ory will validate the `id_token` and create an identity and optionally a session (if configured).
```

2023-09-12 13:47 UTC, Benehiko commented on docs/kratos/social-signin/30_apple.mdx
> +The `id_token` is verified using Apple's publicly available signing keys, available under https://appleid.apple.com/auth/keys.
```suggestion
The `id_token` is verified using Apple's publicly available signing keys. For more information, please take a look at the [Apple documentation](https://appleid.apple.com/auth/keys).
```

2023-09-13 13:04 UTC, Benehiko commented on docs/kratos/social-signin/30_apple.mdx
> +integrate with Ory.
no i meant that the drawbacks shouldn't be listed within the highlevel description.

2023-09-13 13:06 UTC, Benehiko approved these changes

2023-09-14 14:27 UTC, merged