docs: consistency
ory/docs pull request #1577
Opened 2023-10-13 09:40 UTC by aeneasr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-10-13 10:27 UTC, kmherrmann commented on docs/api/consistency.mdx
> +It's important to note that Ory Network operates with a replication lag of approximately 4.8 seconds. This means that even under
```suggestion
It's important to note that Ory Network operates with a replication lag of approximately 5 seconds. This means that even under
```

2023-10-13 10:27 UTC, vinckr requested changes
please headings instead of bolding 🙏 

Removed a lot of the AI speak to make it more readable and clear.

I can also do a style update, lemme know

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +- **Latency**: However, this level may introduce higher latency to your queries, as the system takes the necessary steps to
```suggestion
- **Latency**: However, this level introduces higher latency to your queries, as the system takes the necessary steps to
```

dont beat around the bush

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +- **Use Cases**: Use `full` consistency when access to the most up-to-date data is critical, even if it means slightly longer
```suggestion
- **Use Cases**: Use `full` consistency when access to the most up-to-date data is critical, even if it means longer
```

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +**Definition**: The `eventual` consistency level prioritizes delivering data as swiftly as possible.
```suggestion
**Definition**: The `eventual` consistency level delivers data as fast as possible.
```

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +  might not reflect the very latest updates.
```suggestion
- **Data Freshness**: While `eventual` consistency offers faster query response times, the data can be stale, meaning it
  does not reflect the latest updates.
```

same as above

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +  momentarily less current.
```suggestion
- **Use Cases**: Choose `eventual` consistency when immediate data access is crucial, and you can tolerate data that is not current.
```

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +cases, replication lag might be higher.
```suggestion
`full` consistency, there is still a delay in accessing the latest data due to the replication process. In some
cases, replication lag can be higher.
```

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +to tailor your queries to your specific requirements.
```suggestion
The [Identity List API(../reference/api#tag/identity/operation/listIdentities) in Ory Network supports consistency controls. This means you can choose the consistency level when using the Identity List API.
```

2023-10-13 10:27 UTC, vinckr commented on docs/api/consistency.mdx
> +environment.
I would cut this, it adds nothing IMO.

2023-10-13 10:27 UTC, kmherrmann submitted a review, later dismissed
minor suggestions, thanks!

2023-10-13 10:27 UTC, kmherrmann commented on docs/api/consistency.mdx
> +In conclusion, understanding the consistency levels offered by Ory's APIs is essential for optimizing query performance in a
```suggestion
Understanding the consistency levels offered by Ory's APIs is essential for optimizing query performance in a
```

2023-10-16 08:06 UTC, aeneasr commented on docs/api/consistency.mdx
> +It's important to note that Ory Network operates with a replication lag of approximately 4.8 seconds. This means that even under
It is 4.8 seconds though ;)

2023-10-16 09:00 UTC, merged