feat(hydra): document adding keys to broadcast keys
ory/docs pull request #1785
Opened 2024-07-09 07:58 UTC by jonas-jonas

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2024-08-02 13:52 UTC, vinckr commented
ready for review?

2024-08-02 17:50 UTC, jonas-jonas commented
@vinckr yes, PTAL.

2024-08-06 13:00 UTC, aeneasr requested changes

2024-08-06 13:00 UTC, aeneasr commented on docs/hydra/jwks.mdx
> +For more information on how to create a custom keyset, see the [ory create jwk](../cli/ory-create-jwk) command.
Please link to the file @jonas-jonas (mdx ending)

2024-08-07 11:46 UTC, vinckr approved these changes

2024-08-08 07:34 UTC, aeneasr approved these changes

2024-08-08 07:34 UTC, merged