feat: services and apis
ory/docs pull request #469
Opened 2021-08-18 12:37 UTC by Benehiko

fixes https://github.com/ory-corp/cloud/issues/1362

2021-08-18 13:10 UTC, vinckr requested changes
I think you included some additional files by accident: 
` .idea/codeStyles/Project.xml ` etc.

You probably only want to add `services-api.mdx` and the .png, correct?

2021-08-18 13:10 UTC, vinckr commented on docs/docs/concepts/services-api.mdx
> +in the form of a Web or Native Application.
Is this possible now?
If not I would either omit it or refer to the GitHub issue/roadmap/relevant doc.

2021-08-19 07:58 UTC, Benehiko commented
Will this be adequate for the SDK urls page?

I wanted to add a link to an example application using the sdk's here, but if it's not necessary to do right now we can merge this as is.

2021-08-19 08:00 UTC, aeneasr commented
I think links to here would be good:

- https://www.ory.sh/docs/start-building
- https://www.ory.sh/docs/start-building/server-side-web-app
- https://www.ory.sh/docs/start-building/single-page-app-spa
- https://www.ory.sh/docs/start-building/native-mobile-app
- https://www.ory.sh/docs/start-building/other-languages

2021-08-19 08:00 UTC, aeneasr commented
Use the links you think make sense. We need to add the SDK initalization to those pages then!

2021-08-23 09:45 UTC, aeneasr approved these changes

2021-08-23 09:45 UTC, merged