Update and rename projects.md to open-source-products.md
ory/docs pull request #505
Opened 2021-11-07 21:53 UTC by tacurran

Changed numerous text portions to better explain the Ory Ecosystem. This needs further attention along with FAQ

2021-11-07 22:10 UTC, aeneasr requested changes
Great stuff!

One important thing is to keep file names the same or if they change, ensure the following three things:

1. Update the side bar to link to the new document and delete the old one: https://github.com/ory/docs/blob/master/docs/sidebar.json
2. Update all references to the file you deleted / renamed
3. Add a 302 redirect to the website so Google search results, SEO, and inbound links don't break. Example: https://github.com/ory/web/blob/e3835c77e93786efb3bfd2ee416e7eb36f73a16a/static/_redirects#L257

My suggestion is to keep it the same for this PR!

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +id: products
Regarding IDs and file names, see my comment in the base review comment. This must match the file name, so if this was `projects.md` it needs to be:

```suggestion
id: projects
```

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +Each service works standalone and has an versioned API. Combine these Open Source products for the full
We do not yet have versioned APIs, so how about:

```suggestion
Each service works standalone and has robust REST and sometimes gRPC APIs. Combine these Open Source products for the full
```

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +![Ory Kratos](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-kratos.svg)
Make it a headline:

```suggestion
## ![Ory Kratos](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-kratos.svg)
```

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +![Ory Hydra](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-hydra.svg)
```suggestion
## ![Ory Hydra](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-hydra.svg)
```

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +![Ory Oathkeeper](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-oathkeeper.svg)
```suggestion
## ![Ory Oathkeeper](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-oathkeeper.svg)
```

2021-11-07 22:10 UTC, aeneasr commented on docs/docs/ecosystem/open-source-products.md
> +![Ory Keto](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-keto.svg)
```suggestion
## ![Ory Keto](https://raw.githubusercontent.com/ory/meta/master/static/logos/logo-keto.svg)
```

2021-11-23 14:12 UTC, tacurran commented
@vinckr can you please implement the changes required from @aeneasr ?  I will not get to it this week.

2021-11-26 10:40 UTC, vinckr commented
Hey @aeneasr, I addressed your feedback in this PR: 
https://github.com/ory/docs/pull/515.
I just changed the document title and left the filename the same, since it only shows up in the URL should be fine, right? 
And thus we don't need more renaming, redirects etc.

2021-11-26 12:42 UTC, vinckr approved these changes

2021-12-22 15:00 UTC, aeneasr commented
Merged via #515

2021-12-22 15:00 UTC, closed without merging