fix: added migrate-legacy-policies guide closes #634
ory/docs pull request #724
Opened 2022-03-29 12:50 UTC by gen1us2k

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-03-30 09:59 UTC, aeneasr commented
@zepatrik PTAL

2022-03-30 10:15 UTC, zepatrik requested changes
Nice, sounds like a good migration path. Maybe you could also add a small example for a check? I know that you link to other guides, but it probably helps to see a check in the context of this example.

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +According to the example above we need to create required [namespace](https://www.ory.sh/docs/keto/concepts/namespaces) and [relationship tuple](https://www.ory.sh/docs/keto/concepts/relation-tuples)
Just a tiny naming thing, but we use relation tuple everywhere, not relationship.
```suggestion
According to the example above we need to create required [namespace](https://www.ory.sh/docs/keto/concepts/namespaces) and [relation tuple](https://www.ory.sh/docs/keto/concepts/relation-tuples)
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +- Subjects -> Subject/Subject Sets
```suggestion
- Subjects -> Subject IDs or Subject Sets
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +- Resources -> Namespaces/Objects
```suggestion
- Resources -> Objects scoped by namespaces
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +We need to have `blog_posts` namespace for our example. Let's add the following content to `keto.yml` configuration file. You can find a good template [here](https://github.com/ory/keto/blob/master/c
Don't use links to master but always permalinks.
```suggestion
We need to have `blog_posts` namespace for our example. Let's add the following content to `keto.yml` configuration file. You can find a good template [here](https://github.com/ory/keto/blob/3453d47e67cfe45ad1389a2aa25fd65dfdeb114d/config/keto.yml).
```

Maybe rather link to the config reference? https://www.ory.sh/docs/keto/reference/configuration

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +  name: blog_posts
```suggestion
namespaces:
  - id: 0
    name: blog_posts
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +## Alice relationship tuples
```suggestion
## Alice Relation Tuples
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +## Creating rules using Cli
```suggestion
## Creating Relation Tuples using the CLI
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +This example uses keto cli to create the relation tuple using [write API](../concepts/api-overview#write-apis)
```suggestion
This example uses the Ory Keto CLI to create the relation tuple using the [write API](../concepts/api-overview#write-apis)
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +keto relation-tuple parse alice_policies- --format json | \
```suggestion
keto relation-tuple parse alice_policies --format json | \
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/migrating-legacy-policies.mdx
> +keto relation-tuple parse bob_policies- --format json | \
```suggestion
keto relation-tuple parse bob_policies --format json | \
```

2022-03-30 10:15 UTC, zepatrik commented on docs/keto/guides/upgrade.mdx
> +1. Review breaking changes.
Is this a duplication?

2022-03-30 11:18 UTC, gen1us2k commented on docs/keto/guides/upgrade.mdx
> +1. Review breaking changes.
Yep. Removed it. It was a merge issue

2022-03-30 11:33 UTC, gen1us2k commented
@zepatrik I fixed comments and added check example

2022-04-08 14:25 UTC, zepatrik approved these changes

2022-04-08 14:26 UTC, merged