fix: use latest version in configure&deploy for oathkeeper closes #701
ory/docs pull request #725
Opened 2022-03-29 15:04 UTC by gen1us2k

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-03-29 16:20 UTC, vinckr requested changes
Great, the guide now works with no problems 🎉

2022-03-29 16:20 UTC, vinckr commented on docs/oathkeeper/configure-deploy.md
> +
```suggestion
```

2022-03-29 16:20 UTC, vinckr commented on docs/oathkeeper/configure-deploy.md
> +
```suggestion
```

2022-03-30 09:23 UTC, aeneasr submitted a review, later dismissed
Awesome, the guide works great now! Just a few nitpicks. All newlines in code examples will show up in the rendered HTML as well which looks strange

<img width="1224" alt="Bildschirmfoto 2022-03-30 um 11 22 52" src="https://user-images.githubusercontent.com/3372410/160798201-bf1e376a-5f2f-49b6-87a3-5f7a1fa78280.png">

so we need to remove any unwanted newlines :)

Also there seems to be an image which doesnt work at the end of the file, could you maybe fix that in this pr too?

<img width="1206" alt="Bildschirmfoto 2022-03-30 um 11 22 33" src="https://user-images.githubusercontent.com/3372410/160798283-3c71c601-7c8e-4502-8846-7cc0e81cf140.png">

2022-03-30 09:23 UTC, aeneasr commented on docs/oathkeeper/configure-deploy.md
>  cat << EOF > rules.json
```suggestion
<CodeBlock className="language-shell">{`cat << EOF > rules.json
```

2022-03-30 09:23 UTC, aeneasr commented on docs/oathkeeper/configure-deploy.md
> +`}</CodeBlock>
```suggestion
<CodeBlock className="language-shell">{`docker run oryd/oathkeeper:${useLatestRelease('oathkeeper')} credentials generate --alg RS256 > jwks.json`}</CodeBlock>
```

2022-03-30 09:23 UTC, aeneasr commented on docs/oathkeeper/configure-deploy.md
> +`}</CodeBlock>
```suggestion
<CodeBlock className="language-shell">{`docker pull oryd/oathkeeper:${useLatestRelease('oathkeeper')}`}</CodeBlock>
```

2022-03-30 12:44 UTC, gen1us2k commented
@aeneasr I added missing image

2022-04-07 12:39 UTC, vinckr approved these changes

2022-04-20 16:16 UTC, merged