feat: add documentation for setting up NetID provider
ory/docs pull request #755
Opened 2022-04-13 10:55 UTC by piotrmsc

## Related Issue or Design Document

Added documentation describing how to add NetID as Social Identity Provider to Kratos.

This is a complement to https://github.com/ory/kratos/pull/2394

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-04-13 12:43 UTC, tomekpapiernik approved these changes

2022-04-15 15:20 UTC, aeneasr commented on docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
> +https://playground.projects.oryapis.com/api/kratos/public/self-service/methods/oidc/callback/gitlab
Gitlab? 😅

2022-04-15 15:37 UTC, aeneasr requested changes

2022-04-15 15:37 UTC, aeneasr commented on docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
> +[NetID as an OIDC identity provider](https://docs.gitlab.com/ee/integration/openid_connect_provider.html),
gitlab

2022-04-15 15:37 UTC, aeneasr commented on docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
> +            client_id: .... # Replace this with the OAuth2 Client ID provided by GitLab
gitlab

2022-04-15 15:37 UTC, aeneasr commented on docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
> +            client_secret: .... # Replace this with the OAuth2 Client Secret provided by GitLab
gitlab

2022-04-15 15:37 UTC, aeneasr commented on docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
> +            mapper_url: file:///etc/config/kratos/oidc.gitlab.jsonnet
gitlab

2022-04-19 06:15 UTC, piotrmsc commented
One does not simply type Gitlab 😅  thx @aeneasr, please take a look again :)

2022-04-19 13:38 UTC, aeneasr approved these changes

2022-04-19 13:38 UTC, merged