feat: cors settings on custom domain
ory/docs pull request #793
Opened 2022-05-02 12:45 UTC by Benehiko

## Related Issue or Design Document

Add a guide on setting CORS origins on the project custom domain

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-05-02 16:58 UTC, aeneasr reviewed
The PR has a lot of changes unrelated to it - could you clean it up please to make it easier to review? :)

2022-05-02 17:34 UTC, Benehiko commented
> The PR has a lot of changes unrelated to it - could you clean it up please to make it easier to review? :)

I think this was due to `npm run format`. It hasn't been formatted in a while it seems...

2022-05-02 17:36 UTC, Benehiko commented
I have only edited this file with the added images
https://github.com/ory/docs/blob/07f6284465fae779249af5cc249867011056833c/docs/guides/custom-domains.mdx

2022-05-03 11:21 UTC, aeneasr commented
Could you still reset it? Otherwise there will be tons of merge conflicts with other PRs :/

2022-05-03 14:13 UTC, Benehiko commented
yes i will :)

2022-05-04 12:25 UTC, aeneasr requested changes
Just a minor thing

2022-05-04 12:25 UTC, aeneasr commented on docs/guides/custom-domains.mdx
> +We do not allow setting the CORS origins to be `*` or `null`. You can, however,
localhost is also not allowed

2022-05-04 14:23 UTC, merged