feat: add SPA/vue quickstart
ory/docs pull request #835
Opened 2022-05-27 20:17 UTC by aeneasr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-06-13 12:26 UTC, tomekpapiernik requested changes

2022-06-14 09:39 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +import webm from '../_static/nextjs/screencast.webm'
Oh, that should point to the vue directory!

2022-06-14 09:42 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +npm i --save @ory/client
Node v14 is in maintenance LTS until 2023, so anyone on v14 needs `--save` :)

2022-06-14 09:42 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +Make sure to either `localhost` or `127.0.0.1` but not both when developing locally. If the hostnames are different, Ory's APIs
```suggestion
Make sure to either use `localhost` or `127.0.0.1` but not both when developing locally. If the hostnames are different, Ory's APIs
```

2022-06-14 09:43 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +```
You're right, that can be removed I think. What's nice about the SdkEnvVar is that it is setting the project URL if you're logged in into console for you. We should do that for `--project` as well

2022-06-14 09:44 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +example above). The `--dev` flag disables security checks for easier integration and should not be used when deploying the tunnel
That makes sense, it is referencing `Check for Session in Component`

2022-06-14 09:44 UTC, aeneasr commented on docs/guides/protect-page-login/vue.mdx
> +   `http://localhost:8080`).
SGTM

2022-06-14 13:49 UTC, tomekpapiernik commented
@aeneasr I created a PR with some edits that are focused on language/wording: https://github.com/ory/docs/pull/868
Please have a look and merge it into your PR if you like my updates.

2022-06-14 14:38 UTC, merged