feat: add basic Keto guides
ory/docs pull request #850
Opened 2022-06-02 17:01 UTC by zepatrik

2022-06-08 10:05 UTC, aeneasr commented
And maybe a section that this feature is production ready, but not yet fully released (ui, docs, ...)?

2022-06-08 11:27 UTC, zepatrik commented
> Should we maybe add one example of the Go REST SDK for the two calls you've added?

I'd rather not, as it needs so much boilerplate around the API call with all the imports and setup. IMO it makes more sense to have one go program instead that has comments with the explanation instead. But we can work on that iteratively?

2022-06-14 08:55 UTC, tomekpapiernik requested changes

2022-06-14 08:55 UTC, tomekpapiernik commented on docs/guides/permissions/overview.mdx
> +Following the example above, one could ask:
> the example above
This orientation-based reference isn't clear. It's better to recall the example again to avoid any misunderstandings.

2022-06-14 08:55 UTC, tomekpapiernik commented on docs/guides/permissions/overview.mdx
> +This relation can either be directly defined in the database, or indirectly inferred through transitive relations.
> or indirectly inferred through transitive relations

It's a lot of sophisticated words clustered together which might make understanding this sentence difficult for people of different levels of language proficiency. Could you try to rewrite this sentence to make it simpler? It's better to make it longer or explain something than write content that's hard to understand.

2022-06-14 12:11 UTC, zepatrik commented on docs/guides/permissions/overview.mdx
> +```
Not yet, as the CLI is not compatible with Keto in the Cloud yet.

2022-06-15 09:17 UTC, tomekpapiernik requested changes

2022-06-15 12:59 UTC, zepatrik commented on docs/guides/permissions/overview.mdx
> +other authorization services you know, so lets first clarify a few concepts.
I removed the `paper` in the text, but agree that "implements" is probably better suited.

2022-06-15 12:59 UTC, zepatrik commented on docs/guides/permissions/overview.mdx
> +Learn the dedicated documents to learn more about [subjects](/keto/concepts/subjects.mdx) and [objects](/keto/concepts/objects.mdx).
Haha, I was confused as well...

2022-06-17 08:10 UTC, tomekpapiernik commented on docs/guides/permissions/overview.mdx
> +KETO_WRITE_URL="<your keto write url>"
Alternatively, you could add an explanation of how to get this URL to this document.

2022-06-17 14:45 UTC, aeneasr commented
Can we get this merged? It's been 2 weeks! @tomekpapiernik can you please make the last suggested changes directly to the PR to move forward?

2022-06-20 07:15 UTC, tomekpapiernik commented
@aeneasr @zepatrik the document looks mergeable from my point of view. The only concern I have is this URL name (keto write URL) I mentioned, but if you don't think it's a problem then go ahead and merge it. I don't know what else to call it, just voicing my concern. I'll approve the PR now so you can do as you see fit.

2022-06-20 07:24 UTC, tomekpapiernik approved these changes

2022-06-20 07:50 UTC, merged

2022-06-20 08:27 UTC, zepatrik commented on docs/guides/permissions/overview.mdx
> +KETO_WRITE_URL="<your keto write url>"
It is the URL of where the Keto write API is available. Let's update this at a later point, I currently also don't know what a better description would be.