docs: add context to hooks auth snippets
ory/docs pull request #947
Opened 2022-08-09 16:20 UTC by jonas-jonas

The current documentation for auth in kratos' web hooks lacks context and is difficult to understand ([example](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1660048260538329)) if you don't know what to look for. This PR adds some context around the snippets and (hopefully) makes this topic a bit clearer.

Also, I removed some stray " (quotation mark) from the path in code snippets on the page.

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments

2022-08-09 16:25 UTC, kmherrmann submitted a review, later dismissed
Thanks for doing this!

2022-08-10 06:43 UTC, tomekpapiernik requested changes
You must either leave both of the `"` in `title=` or remove both of them ;)

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 06:43 UTC, tomekpapiernik commented on docs/kratos/self-service/hooks.mdx
> +```yaml title=path/to/my/kratos.config.yml"
```suggestion
```yaml title=path/to/my/kratos.config.yml
```

2022-08-10 07:02 UTC, jonas-jonas commented
@tomekpapiernik right, apparently the quotes were only missing on the first few snippets. I added them around all of them. It should be good now.

2022-08-10 07:39 UTC, tomekpapiernik approved these changes

2022-08-10 07:40 UTC, merged