docs: explain insecure Keto CLI flag
ory/docs pull request #967
Opened 2022-08-25 14:26 UTC by hperl

This PR quickly explains the usage of the new --insecure flags in the Keto CLI.

Blocked by https://github.com/ory/keto/pull/991

2022-08-25 14:36 UTC, zepatrik submitted a review, later dismissed
Lets merge this once the upstream Keto change is done.

2022-08-26 12:35 UTC, tomekpapiernik requested changes
Don't be afraid to speak from the position of authority in the docs :) Replace "is necessary" with "you must" to stress the importance of this setting. 

"newer versions of the Keto CLI" sounds ambiguous - which version of the CLI you consider "newer"? Newer than what? Use specific version IDs for clarity.

Finally, instead of adding this information into parentheses, please add it as an admonition. If you feel that this information is very important, use `:::warning`. If not, `:::info` or `::note` should suffice.

2022-12-06 09:48 UTC, tomekpapiernik commented
@hperl Can you please finish this up? My comment still stands. Thanks.

2022-12-06 11:29 UTC, hperl commented
> @hperl Can you please finish this up? My comment still stands. Thanks.

Should be done now :tada:

2022-12-06 12:26 UTC, tomekpapiernik approved these changes

2022-12-06 12:26 UTC, merged