docs: add guide for importing SCrypt passwords
ory/docs pull request #978
Opened 2022-08-30 19:25 UTC by LandonPattison

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments
Added documentation for showing how to import SCrypt algorithm passwords
PR to implement scrypt algorithm importing: https://github.com/ory/kratos/pull/2689

2022-08-31 06:12 UTC, tomekpapiernik requested changes
Thanks for your contribution! It seems that you forgot to format the documents since the `Format / format (pull_request)` CI step fails. 

Please run 
```
npm i
npm run format
```
and then commit the formatted files to fix this.

2022-08-31 19:21 UTC, kevgo reviewed
Thanks for adding this! A few syntax improvements below.

2022-08-31 19:21 UTC, kevgo commented on docs/kratos/concepts/credentials/username-email-password.mdx
> +Ory Kratos doesn't hash passwords by SCrypt but can compare stored SCrypt hash and migrate to configured hasher
```suggestion
Ory Kratos doesn't hash passwords by SCrypt but can compare stored SCrypt hashes and migrate to configured hasher
```

2022-08-31 19:21 UTC, kevgo commented on docs/kratos/concepts/credentials/username-email-password.mdx
> +- `parrelization`(`number`): parallelization parameter (must satisfy r * p < 2³⁰)
```suggestion
- `parallelization`(`number`): parallelization parameter (must satisfy r * p < 2³⁰)
```

2022-09-05 06:38 UTC, LandonPattison commented on docs/kratos/concepts/credentials/username-email-password.mdx
> +Ory Kratos doesn't hash passwords by SCrypt but can compare stored SCrypt hash and migrate to configured hasher
Fixed :)

2022-09-05 06:40 UTC, LandonPattison commented on docs/kratos/concepts/credentials/username-email-password.mdx
> +- `parrelization`(`number`): parallelization parameter (must satisfy r * p < 2³⁰)
fixed :)

2022-09-05 09:08 UTC, tomekpapiernik commented
Looks okay now, good to merge once the related code is merged too. @aeneasr

2022-09-05 09:09 UTC, tomekpapiernik approved these changes

2022-09-08 19:44 UTC, merged